name: Format with Prettier
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.x
          run_install: true

      - name: Format prettier
        run: pnpm run format

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Format code with Prettier"
